### ISSUE TITLE
Thread.html 404 File not Found

### ISSUE THREAD

**Issue by SalamanderSandwich** [murrty/YChanEx#3]
Links for full sized images points to FILENAME.EXT.EXT causing every file to fail. Only tried with 4chan on /a/ and /b/.

**Comment by murrty** [comment]
I couldn't replicate the issue. However, some files did return 404 because it wasn't replace properly with original file names. Maybe I fixed it?

**Comment by murrty** [comment]
Fixed (as far as I know) in v1.69, keeping open for a bit just in case.

**Comment by SalamanderSandwich** [comment]
Still there. I think it's an issue with the save original file names setting.

**Comment by murrty** [comment]
I've tested it before, with my settings (original + prevent dupes) it would spit out a file without an extension. Anyway, I added your pull request into the master.
