### ISSUE TITLE
System.NullReferenceException fourChan.cs

### ISSUE THREAD

**Issue by SalamanderSandwich** [murrty/YChanEx#4]
Exception happens here https://github.com/murrty/YChanEx/blob/121bc69b80a8ac75a9e2d9d7f5aedec7cb4d9f21/Chan%20Classes/fourChan.cs#L181

Found on /a/ but I think the error I was getting on Issue https://github.com/murrty/YChanEx/issues/2 is the same and was found on /b/

**Comment by murrty** [comment]
I released an update, hopefully my theory that the exception was referencing was an empty XML file, but I will keep it open for a short while.
