### ISSUE TITLE
8kun older urls issue

### ISSUE THREAD

**Issue by ASLad-1** [murrty/YChanEx#8]
Hi, i downloaded YChanEx and i have encountered an error in the 8kun image url that tries to download from a thread created from the older 8chan, delivering a 404 error.

It tries to download from normal, while the URL it's something like this:

"https://media.8kun.top/" + ThreadBoard + "/src/"

(https://media.8kun.top/biz/src/1466793074555.png)

Have a nice day.

**Comment by murrty** [comment]
show me an example thread, and I'll need to see if they specify it's the api returns different result.

**Comment by ASLad-1** [comment]
Sure, the thread in question i refered previously is this.

https://8kun.top/biz/res/1174.html

I tested if every image in that thread uses the same url structure, and it does.

Have a nice day.

**Comment by murrty** [comment]
thank you for giving me the link.

it seems like the one you gave me includes a field "fpath", which if set to 1 should be a flag to use the "newer" file_store path. i can easily account for it, the api is the same otherwise.
